#!/usr/bin/env python
result = None

# The base function block used for grading
def grade():
  global result
  if (usercode()) == 'Hello World!':
    result = True
  else:
    result = False
  return result
